server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/test
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          required-acks: all
          auto-create-topics: false
          transaction:
            transaction-id-prefix: wallet-
            producer:
              configuration:
                transaction:
                  timeout:
                    ms: 30000

logging:
  level:
    org:
      springframework:
        transaction: TRACE
        orm:
          jpa: DEBUG
        kafka: TRACE
